// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "pie":return img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
...........6.......6............
............666.666.............
.......eeeeee66666eeeeee........
....eeee444444222444444eeee.....
....5aeee4444422244444eeea5.....
....5a3aeeeeeeeeeeeeeeea3a5.....
....55a3a3a3a3a3a3a3a3a3a55.....
.....5a3a3a3a3a3a3a3a3a3a5......
.....55a3a3a3a3a3a3a3a3a5.......
......553a3a3a3a3a3a3a355.......
......5aaaaaaaaaaaaaaaaaa5......
......55555555555555555555......
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
